
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1-namespace-owner-reference
  failurePolicy: Fail
  name: owner.namespace.capsule.clastix.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - namespaces
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1-service-labels
  failurePolicy: Ignore
  name: service.labels.capsule.clastix.io
  rules:
  - apiGroups:
    - ""
    - discovery.k8s.io
    apiVersions:
    - v1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
    - endpoints
    - endpointslices

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validating-ingress
  failurePolicy: Fail
  name: ingress-v1beta1.capsule.clastix.io
  rules:
  - apiGroups:
    - networking.k8s.io
    - extensions
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validating-ingress
  failurePolicy: Fail
  name: ingress-v1.capsule.clastix.io
  rules:
  - apiGroups:
    - networking.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-v1-namespace-quota
  failurePolicy: Fail
  name: quota.namespace.capsule.clastix.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - namespaces
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validating-v1-network-policy
  failurePolicy: Fail
  name: validating.network-policy.capsule.clastix.io
  rules:
  - apiGroups:
    - networking.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - networkpolicies
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validating-v1-pvc
  failurePolicy: Fail
  name: pvc.capsule.clastix.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - persistentvolumeclaims
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validating-v1-tenant
  failurePolicy: Fail
  name: tenant.capsule.clastix.io
  rules:
  - apiGroups:
    - capsule.clastix.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - tenants
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validating-v1-namespace-tenant-prefix
  failurePolicy: Fail
  name: prefix.namespace.capsule.clastix.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - namespaces
